/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import "./globals.css";
import ApolloProviderWrapper from "../providers/ApolloProvider";
import ClientSessionProvider from "../providers/ClientSessionProvider"; // Import the wrapper
import { CurrencyProvider } from "@/providers/CurrencyContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ClientSessionProvider>
          <ApolloProviderWrapper>
            <CurrencyProvider>
              <div>
                {children}
              </div>
            </CurrencyProvider>
          </ApolloProviderWrapper>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
